/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EcommerceImport } from './routes/_ecommerce'
import { Route as AdminImport } from './routes/_admin'
import { Route as EcommerceIndexImport } from './routes/_ecommerce/index'
import { Route as EcommerceProductImport } from './routes/_ecommerce/product'
import { Route as AdminAdminIndexImport } from './routes/_admin/admin/index'
import { Route as AdminAdminFiltersImport } from './routes/_admin/admin/filters'
import { Route as AdminAdminProductsIndexImport } from './routes/_admin/admin/products/index'
import { Route as AdminAdminCategoriesIndexImport } from './routes/_admin/admin/categories/index'
import { Route as AdminAdminProductsCreateImport } from './routes/_admin/admin/products/create'
import { Route as AdminAdminCategoriesCreateImport } from './routes/_admin/admin/categories/create'
import { Route as AdminAdminCategoriesEditCategoryIdImport } from './routes/_admin/admin/categories/edit/$categoryId'

// Create/Update Routes

const EcommerceRoute = EcommerceImport.update({
  id: '/_ecommerce',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
} as any)

const EcommerceIndexRoute = EcommerceIndexImport.update({
  path: '/',
  getParentRoute: () => EcommerceRoute,
} as any)

const EcommerceProductRoute = EcommerceProductImport.update({
  path: '/product',
  getParentRoute: () => EcommerceRoute,
} as any)

const AdminAdminIndexRoute = AdminAdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAdminFiltersRoute = AdminAdminFiltersImport.update({
  path: '/admin/filters',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAdminProductsIndexRoute = AdminAdminProductsIndexImport.update({
  path: '/admin/products/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAdminCategoriesIndexRoute = AdminAdminCategoriesIndexImport.update({
  path: '/admin/categories/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAdminProductsCreateRoute = AdminAdminProductsCreateImport.update({
  path: '/admin/products/create',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAdminCategoriesCreateRoute = AdminAdminCategoriesCreateImport.update(
  {
    path: '/admin/categories/create',
    getParentRoute: () => AdminRoute,
  } as any,
)

const AdminAdminCategoriesEditCategoryIdRoute =
  AdminAdminCategoriesEditCategoryIdImport.update({
    path: '/admin/categories/edit/$categoryId',
    getParentRoute: () => AdminRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_ecommerce': {
      id: '/_ecommerce'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof EcommerceImport
      parentRoute: typeof rootRoute
    }
    '/_ecommerce/product': {
      id: '/_ecommerce/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof EcommerceProductImport
      parentRoute: typeof EcommerceImport
    }
    '/_ecommerce/': {
      id: '/_ecommerce/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof EcommerceIndexImport
      parentRoute: typeof EcommerceImport
    }
    '/_admin/admin/filters': {
      id: '/_admin/admin/filters'
      path: '/admin/filters'
      fullPath: '/admin/filters'
      preLoaderRoute: typeof AdminAdminFiltersImport
      parentRoute: typeof AdminImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/admin/categories/create': {
      id: '/_admin/admin/categories/create'
      path: '/admin/categories/create'
      fullPath: '/admin/categories/create'
      preLoaderRoute: typeof AdminAdminCategoriesCreateImport
      parentRoute: typeof AdminImport
    }
    '/_admin/admin/products/create': {
      id: '/_admin/admin/products/create'
      path: '/admin/products/create'
      fullPath: '/admin/products/create'
      preLoaderRoute: typeof AdminAdminProductsCreateImport
      parentRoute: typeof AdminImport
    }
    '/_admin/admin/categories/': {
      id: '/_admin/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminCategoriesIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/admin/products/': {
      id: '/_admin/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/admin/categories/edit/$categoryId': {
      id: '/_admin/admin/categories/edit/$categoryId'
      path: '/admin/categories/edit/$categoryId'
      fullPath: '/admin/categories/edit/$categoryId'
      preLoaderRoute: typeof AdminAdminCategoriesEditCategoryIdImport
      parentRoute: typeof AdminImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AdminRoute: AdminRoute.addChildren({
    AdminAdminFiltersRoute,
    AdminAdminIndexRoute,
    AdminAdminCategoriesCreateRoute,
    AdminAdminProductsCreateRoute,
    AdminAdminCategoriesIndexRoute,
    AdminAdminProductsIndexRoute,
    AdminAdminCategoriesEditCategoryIdRoute,
  }),
  EcommerceRoute: EcommerceRoute.addChildren({
    EcommerceProductRoute,
    EcommerceIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_admin",
        "/_ecommerce"
      ]
    },
    "/_admin": {
      "filePath": "_admin.tsx",
      "children": [
        "/_admin/admin/filters",
        "/_admin/admin/",
        "/_admin/admin/categories/create",
        "/_admin/admin/products/create",
        "/_admin/admin/categories/",
        "/_admin/admin/products/",
        "/_admin/admin/categories/edit/$categoryId"
      ]
    },
    "/_ecommerce": {
      "filePath": "_ecommerce.tsx",
      "children": [
        "/_ecommerce/product",
        "/_ecommerce/"
      ]
    },
    "/_ecommerce/product": {
      "filePath": "_ecommerce/product.tsx",
      "parent": "/_ecommerce"
    },
    "/_ecommerce/": {
      "filePath": "_ecommerce/index.tsx",
      "parent": "/_ecommerce"
    },
    "/_admin/admin/filters": {
      "filePath": "_admin/admin/filters.tsx",
      "parent": "/_admin"
    },
    "/_admin/admin/": {
      "filePath": "_admin/admin/index.tsx",
      "parent": "/_admin"
    },
    "/_admin/admin/categories/create": {
      "filePath": "_admin/admin/categories/create.tsx",
      "parent": "/_admin"
    },
    "/_admin/admin/products/create": {
      "filePath": "_admin/admin/products/create.tsx",
      "parent": "/_admin"
    },
    "/_admin/admin/categories/": {
      "filePath": "_admin/admin/categories/index.tsx",
      "parent": "/_admin"
    },
    "/_admin/admin/products/": {
      "filePath": "_admin/admin/products/index.tsx",
      "parent": "/_admin"
    },
    "/_admin/admin/categories/edit/$categoryId": {
      "filePath": "_admin/admin/categories/edit/$categoryId.tsx",
      "parent": "/_admin"
    }
  }
}
ROUTE_MANIFEST_END */
